<a href="https://colab.research.google.com/github/Shaurya-XD/Data_Analysis_Anime/blob/main/Anime_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('anime.csv')
df.head(10)

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5     6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6     7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7     8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8     9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9    10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03

In [ ]:
def extract_ep(txt):
  check = False
  ep = ""
  for i in txt:
    if i == ')':
      break
    if check == True:
      ep += i
    if i == '(':
      check = True

  return ep

df['Episodes'] = df['Title'].apply(extract_ep)
df['Episodes'] = df['Episodes'].str.replace(" eps", "")
df['Episodes'] = df['Episodes'].astype(int)
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

In [ ]:
df.loc[3]['Title']

'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'

In [ ]:
def extract_time(txt):
  check = False
  count = 19
  time = ""
  for i in txt:
    if (check == True) and (count > 0):
      time += i
      count -= 1
    if i == ')':
      check = True
  return time

df["Time_Line"] = df['Title'].apply(extract_time)
df.head()

,Rank,Title,Score,Episodes,Time_Line
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [ ]:
import pandas as pd

def get_months(duration):
    start, end = duration.split(" - ")

    start = pd.to_datetime(start)
    end = pd.to_datetime(end)

    months = (end.year - start.year) * 12 + (end.month - start.month)

    return months

df['Months'] = df['Time_Line'].apply(get_months)
df.head()

,Rank,Title,Score,Episodes,Time_Line,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

In [ ]:
bool_max = df['Score'] == df['Score'].max()
df[bool_max]

,Rank,Title,Score,Episodes,Time_Line,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,15

In [ ]:
bool_ep = df['Episodes'] == df['Episodes'].max()
df[bool_ep]

,Rank,Title,Score,Episodes,Time_Line,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,47